# Generated by Django 5.1 on 2024-08-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_apiconfiguration_huggingface_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='business_value',
            new_name='insight',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='sql',
        ),
    ]
