# Generated by Django 5.1 on 2024-08-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_business_value_insight_insight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='insight',
        ),
        migrations.AddField(
            model_name='insight',
            name='business_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='sql',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
