# Generated by Django 5.1 on 2024-08-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_insight_insight_insight_business_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='insights',
            field=models.ManyToManyField(related_name='messages', to='chat.insight'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='business_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insight',
            name='sql',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
