# Generated by Django 5.1 on 2024-08-25 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_insight_message_message_insights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='insights',
        ),
        migrations.AddField(
            model_name='insight',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='chat.message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insight',
            name='business_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
