# Generated by Django 5.1 on 2024-08-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_insights_insight_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
