# Generated by Django 5.1 on 2024-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfiguration',
            name='model_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
